#%RAML 1.0
title: copycat
version: v0.0
protocols: [ HTTP, HTTPS ]
baseUri: http://localhost

types:
  copyCatImports: !include copycatimports.json
  copyCatProfile: !include copycatprofile.json
  copyCatCollection: !include copycatcollection.json
  error: !include raml-util/schemas/error.schema
  errors: !include raml-util/schemas/errors.schema

traits:
  pageable: !include raml-util/traits/pageable.raml
  searchable: !include raml-util/traits/searchable.raml

/copycat:
  /imports:
    post:
      description: Import record from external system
      body:
        application/json:
          type: copyCatImports
      responses:
        204:
          description: Imported OK
        400:
          description: Import error
          body:
            application/json:
              type: errors
        500:
          description: Internal error
          body:
            text/plain:
  /profiles:
    post:
      description: Create profile
      body:
        application/json:
          type: copyCatProfile
      responses:
        201:
          description: Created OK
          headers:
            Location:
              description: URI of profile
          body:
            application/json:
              type: copyCatProfile
        400:
          description: Error in usage
          body:
            text/plain:
        500:
          description: Internal error
          body:
            text/plain:
    get:
      is: [pageable,
       searchable: {
             description: "search profiles",
             example: "name = loc"}
      ]
      description: Get profiles
      responses:
        200:
          description: Get collection OK
          body:
            application/json:
              type: copyCatCollection
        400:
          description: Error in usage
          body:
            text/plain:
        500:
          description: Internal error
          body:
            text/plain:
    /{id}:
      get:
        description: Get profile
        responses:
          200:
            description: retrieved OK
            body:
              application/json:
                type: copyCatProfile
          400:
            description: User error
            body:
              text/plain:
          404:
            description: Not found
            body:
              text/plain:
          500:
            description: Internal error
            body:
              text/plain:
      put:
        description: Update target profile
        body:
          application/json:
            type: copyCatProfile
        responses:
          204:
            description: updated OK
          400:
            description: User error
            body:
              text/plain:
          404:
            description: Not found
            body:
              text/plain:
          500:
            description: Internal error
            body:
              text/plain:
      delete:
        description: Delete target profile
        responses:
          204:
            description: deleted OK
          400:
            description: User error
            body:
              text/plain:
          404:
            description: Not found
            body:
              text/plain:
          500:
            description: Internal error
            body:
              text/plain:
